/**
 * Constants — nexus-similarity-search-api
 * Auto-generated by NEXUS mcp_wrapper_generator. Do not edit by hand;
 * regenerate from the ToolSpec if the underlying API changes.
 */

export const SERVER_NAME = "similarity-search-api-mcp-server";
export const SERVER_DISPLAY_NAME = "nexus-similarity-search-api";
export const SERVER_VERSION = "1.0.0";

/** Truncate any single tool response beyond this many characters,
 *  to keep agent context usage bounded and predictable. */
export const CHARACTER_LIMIT = 25_000;

/** Base URL of the NEXUS core service (the Python/FastAPI backend
 *  that FORGE generated in core/). This MCP server is a thin,
 *  protocol-compliant adapter over it — never business logic. */
export const CORE_BASE_URL = process.env.NEXUS_CORE_BASE_URL ?? "{CORE_BASE_URL}";

/** Per-request timeout to the core service. */
export const CORE_TIMEOUT_MS = Number(process.env.NEXUS_CORE_TIMEOUT_MS ?? 10_000);

/** Retry policy for transient core-service failures. */
export const CORE_MAX_RETRIES = 2;
export const CORE_RETRY_BASE_DELAY_MS = 250;
