/**
 * Tool registration -- one entry per capability exposed by this MCP server.
 * Business logic lives in the core service; these handlers only validate,
 * call, and shape the response for agent consumption.
 *
 * --- NEXUS PATCH mcp_tool_grounding_similarity_search ---
 * Originally had 5 tools; 4 called endpoints (/v1/similarity/rank-nmi-cosine,
 * pairwise-nmi-matrix, pair-significance, dimension-redundancy,
 * calibrate-hybrid-weight) that do not exist anywhere in the core service --
 * the tool_spec phase and the core API code were generated by independent
 * Claude calls with no shared memory (see commit 55c1f49 for the forward
 * fix). Only rank_embeddings_by_nmi_cosine has a real equivalent
 * (POST /similarity/search); the other 4 described features never built
 * (NxN matrix, dimension redundancy, triplet calibration) and were removed
 * rather than left pointing at 404s.
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { callCore } from "./coreClient.js";
import { CoreServiceError } from "./types.js";
import { CHARACTER_LIMIT } from "./constants.js";
import { RankEmbeddingsByNmiCosineInputSchema } from "./schemas.js";
import type { RankEmbeddingsByNmiCosineInput } from "./types.js";

export function registerTools(server: McpServer): void {

  server.registerTool(
    "nexus_similarity_search_api_rank_embeddings_by_nmi_cosine",
    {
      title: "NMI-Cosine Hybrid Ranking",
      description: `Ranks a corpus of embeddings against a query vector using a composite score that blends cosine similarity with entropy-calibrated Normalized Mutual Information (NMI). Stateless per-call scoring, no vector database required. Use when you need a similarity ranking over an inline corpus. Do NOT use for corpora larger than 500,000 items in a single call, or when you need exact nearest-neighbor search rather than a hybrid statistical score.

Returns (JSON):
{
  "results": [{"id": "...", "composite_score": 0.0, "cosine_similarity": 0.0, "nmi_score": 0.0, "rank": 1}],
  "calibrated_alpha": 0.0,
  "corpus_entropy": 0.0,
  "query_id": "...",
  "corpus_size": 0,
  "latency_ms": 0.0,
  "request_fingerprint": "..."
}

Error handling:
  - Throws with a clear message if the core service is unreachable, times out,
    or returns a non-2xx status. The message includes the upstream request_id
    when available, for support correlation.`,
      inputSchema: RankEmbeddingsByNmiCosineInputSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ query_vector, corpus_vectors, corpus_ids, top_k, nmi_bins, alpha_override }: RankEmbeddingsByNmiCosineInput) => {
      try {
        const output = await callCore<Record<string, unknown>>(
          "/similarity/search",
          "POST",
          {
            query: { id: "query", vector: query_vector },
            corpus: corpus_ids.map((id, i) => ({ id, vector: corpus_vectors[i] })),
            top_k,
            nmi_bins,
            alpha_override,
          },
        );

        const text = JSON.stringify(output, null, 2);
        const truncated = text.length > CHARACTER_LIMIT;
        const display = truncated
          ? text.slice(0, CHARACTER_LIMIT) +
            `\n\n... [truncated, ${text.length - CHARACTER_LIMIT} more characters. ` +
            `Narrow your query or request fewer results.]`
          : text;

        return {
          content: [{ type: "text" as const, text: display }],
          structuredContent: output,
        };
      } catch (err) {
        if (err instanceof CoreServiceError) {
          return {
            content: [{
              type: "text" as const,
              text: `Error calling nexus_similarity_search_api_rank_embeddings_by_nmi_cosine (${err.code}): ${err.message}` +
                (err.requestId ? ` [request_id=${err.requestId}]` : ""),
            }],
            isError: true,
          };
        }
        throw err;
      }
    },
  );
}
