"""
nexus-similarity-search-api — CrewAI Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.crewai_tool import RankEmbeddingsByNmiCosineTool

    @agent
    class MyAgent(Agent):
        tools = [RankEmbeddingsByNmiCosineTool()]
"""

from typing import Any
from crewai_tools import BaseTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class RankEmbeddingsByNmiCosineInput(BaseModel):
    query_vector: list[float] = Field(..., description='Dense embedding vector to rank against the corpus. Must be the same dimensionality as all corpus_vectors. Values should be raw floats, not pre-normalized.')
    corpus_vectors: list[list[float]] = Field(..., description='List of candidate embedding vectors. Each inner array must share the same dimensionality as query_vector. Minimum 10 vectors required for valid bootstrap estimation.')
    corpus_ids: list[str] = Field(..., description='Opaque identifiers for each vector in corpus_vectors, returned in the ranking response. Length must exactly match corpus_vectors. Use stable external IDs (document IDs, chunk hashes, etc.).')
    discretization_bins: float = Field(None, description='Number of equal-width bins used to discretize continuous embedding dimensions before computing joint entropy. Higher values increase NMI resolution but also estimation variance. Recommended range 4-20; values above 30 degrade NMI reliability on typical embedding sizes.')
    bootstrap_iterations: float = Field(None, description='Number of bootstrap resampling iterations per pair used to compute the 95% confidence interval on the hybrid score and the p-value under the null of no mutual information. Higher values narrow confidence intervals at linear compute cost. Minimum 100 for valid p-values.')
    top_k: float = Field(None, description='Number of top-ranked results to return, ordered by descending hybrid score. Must be <= len(corpus_vectors). Set to 0 to return all ranked results.')
    alpha: float = Field(None, description='Significance level threshold for p-value filtering. Results with p_value > alpha are flagged as statistically insignificant in the response but are still returned unless filter_insignificant is true. Standard values: 0.05 or 0.01.')
    filter_insignificant: bool = Field(None, description='If true, results where p_value > alpha are excluded from the returned ranking entirely. If false, they are included but flagged. Set to false when you need ranked output regardless of significance for downstream reranking.')
    nmi_cosine_weight: float = Field(None, description='Convex combination weight w in hybrid_score = w * nmi + (1-w) * cosine_similarity. Set closer to 1.0 to emphasize statistical dependency over geometric proximity. Set to 0.5 for balanced scoring. Do not set below 0.1 if the goal is statistical validation — the p-value computation is always NMI-based regardless of this weight.')


class RankEmbeddingsByNmiCosineTool(BaseTool):
    name: str = "nexus_similarity_search_api_rank_embeddings_by_nmi_cosine"
    description: str = 'Ranks a corpus of embeddings against a query vector using a hybrid score that combines cosine similarity with Normalized Mutual Information (NMI) computed via joint-entropy estimation over discretized embedding dimensions. Returns per-pair p-values from bootstrap confidence intervals. Use when you need statistically validated similarity rankings where you must distinguish real dependency patterns from random correlation. Do NOT use for real-time latency-sensitive paths (>500 vectors adds bootstrap overhead), for pure nearest-neighbor ANN tasks where p-values are irrelevant, or when corpus vectors are fewer than 10 (bootstrap intervals become unreliable).'
    args_schema: type[BaseModel] = RankEmbeddingsByNmiCosineInput

    def _run(self, query_vector, corpus_vectors, corpus_ids, discretization_bins, bootstrap_iterations, top_k, alpha, filter_insignificant, nmi_cosine_weight) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_rank_embeddings_by_nmi_cosine", {"query_vector": query_vector, "corpus_vectors": corpus_vectors, "corpus_ids": corpus_ids, "discretization_bins": discretization_bins, "bootstrap_iterations": bootstrap_iterations, "top_k": top_k, "alpha": alpha, "filter_insignificant": filter_insignificant, "nmi_cosine_weight": nmi_cosine_weight})

class EstimatePairwiseNmiMatrixInput(BaseModel):
    vectors: list[list[float]] = Field(..., description='Set of embedding vectors for which to compute the pairwise NMI matrix. All vectors must share identical dimensionality. N must be between 2 and 80.')
    vector_ids: list[str] = Field(..., description='Identifiers for each vector in vectors, used to label the matrix rows and columns in the response. Length must exactly match vectors.')
    discretization_bins: float = Field(None, description='Number of bins for discretizing continuous dimensions before joint-entropy estimation. Shared across all pairs. Same semantics as in rank_embeddings_by_nmi_cosine.')
    bootstrap_iterations: float = Field(None, description='Bootstrap resampling iterations applied to each pair. Because this endpoint computes N*(N-1)/2 pairs, keep this lower than in single-pair calls to control latency. Minimum 100 required for valid p-values.')
    alpha: float = Field(None, description='Significance threshold. Pairs with p_value > alpha are flagged as statistically independent in the matrix response.')


class EstimatePairwiseNmiMatrixTool(BaseTool):
    name: str = "nexus_similarity_search_api_estimate_pairwise_nmi_matrix"
    description: str = "Computes the full N×N Normalized Mutual Information matrix for a set of embeddings, returning each cell's NMI score along with a bootstrap-derived p-value under the null hypothesis H0: NMI=0 (independence). Use for clustering pre-analysis, redundancy detection across a document set, or graph-of-similarity construction where edge weights must be statistically grounded. Do NOT use when N > 80 — O(N^2 * bootstrap_iterations) cost makes it prohibitive; use rank_embeddings_by_nmi_cosine in batches instead. Not suitable as a real-time retrieval path."
    args_schema: type[BaseModel] = EstimatePairwiseNmiMatrixInput

    def _run(self, vectors, vector_ids, discretization_bins, bootstrap_iterations, alpha) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_estimate_pairwise_nmi_matrix", {"vectors": vectors, "vector_ids": vector_ids, "discretization_bins": discretization_bins, "bootstrap_iterations": bootstrap_iterations, "alpha": alpha})

class ScoreCandidatePairSignificanceInput(BaseModel):
    vector_a: list[float] = Field(..., description='First embedding vector of the pair. Must share dimensionality with vector_b.')
    vector_b: list[float] = Field(..., description='Second embedding vector of the pair. Must share dimensionality with vector_a.')
    discretization_bins: float = Field(None, description="Bins for joint-entropy discretization of the two vectors' dimensions.")
    bootstrap_iterations: float = Field(None, description='Resampling iterations for confidence interval and p-value on the NMI estimate. For a single pair, 500+ iterations are affordable and recommended for tight intervals.')
    nmi_cosine_weight: float = Field(None, description='Weight w for hybrid_score = w * nmi + (1-w) * cosine. Same semantics as in rank_embeddings_by_nmi_cosine.')


class ScoreCandidatePairSignificanceTool(BaseTool):
    name: str = "nexus_similarity_search_api_score_candidate_pair_significance"
    description: str = 'Computes the hybrid NMI-cosine score and bootstrap p-value for exactly one (query, candidate) embedding pair. Use when you already have a candidate from an external ANN index and need to validate whether the cosine similarity reflects a real statistical dependency — i.e., post-retrieval significance gating. Do NOT use to rank a corpus (use rank_embeddings_by_nmi_cosine instead); calling this in a loop over hundreds of candidates is wasteful because it cannot amortize discretization costs across the corpus.'
    args_schema: type[BaseModel] = ScoreCandidatePairSignificanceInput

    def _run(self, vector_a, vector_b, discretization_bins, bootstrap_iterations, nmi_cosine_weight) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_score_candidate_pair_significance", {"vector_a": vector_a, "vector_b": vector_b, "discretization_bins": discretization_bins, "bootstrap_iterations": bootstrap_iterations, "nmi_cosine_weight": nmi_cosine_weight})

class DetectEmbeddingDimensionRedundancyInput(BaseModel):
    sample_vectors: list[list[float]] = Field(..., description='Representative sample of embedding vectors from the target space. Used to estimate marginal and joint entropy across dimensions. Minimum 50 samples recommended for stable entropy estimates; maximum 1000.')
    redundancy_nmi_threshold: float = Field(None, description='NMI value above which two dimensions are considered redundant with each other and grouped into the same cluster. NMI=1.0 means perfect dependency; 0.0 means independence. Values between 0.6 and 0.85 are typical for flagging actionable redundancy.')
    discretization_bins: float = Field(None, description='Bins for discretizing each scalar dimension value across the sample before joint-entropy computation.')
    alpha: float = Field(None, description='Significance level. Dimension pairs whose NMI p-value > alpha are excluded from redundancy clusters even if their NMI point estimate exceeds redundancy_nmi_threshold.')


class DetectEmbeddingDimensionRedundancyTool(BaseTool):
    name: str = "nexus_similarity_search_api_detect_embedding_dimension_redundancy"
    description: str = 'Identifies redundant dimensions within a single embedding space by computing pairwise NMI across all D*(D-1)/2 dimension pairs of the provided sample vectors, returning clusters of highly dependent dimensions (NMI above threshold) and a suggested reduced dimensionality. Use before building a similarity pipeline to prune embedding dimensions that carry no additional information — reduces downstream NMI estimation variance and cosine noise. Do NOT use for embeddings with D > 256 (quadratic in D); not intended for runtime retrieval calls, only for offline embedding space analysis.'
    args_schema: type[BaseModel] = DetectEmbeddingDimensionRedundancyInput

    def _run(self, sample_vectors, redundancy_nmi_threshold, discretization_bins, alpha) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_detect_embedding_dimension_redundancy", {"sample_vectors": sample_vectors, "redundancy_nmi_threshold": redundancy_nmi_threshold, "discretization_bins": discretization_bins, "alpha": alpha})

class CalibrateNmiCosineWeightForCorpusInput(BaseModel):
    triplets: list[list[float]] = Field(..., description='Flattened calibration triplets. Each triplet is encoded as three consecutive rows: [query_vector, positive_vector, negative_vector]. Total rows must be a multiple of 3. Minimum 15 triplets (45 rows); maximum 300 triplets (900 rows).')
    weight_search_grid_size: float = Field(None, description='Number of evenly spaced w values in [0.0, 1.0] to evaluate. A grid of 20 evaluates w in {0.0, 0.05, 0.10, ..., 1.0}. Higher values yield finer-grained optima at linear cost.')
    discretization_bins: float = Field(None, description='Bins for joint-entropy estimation used during calibration scoring. Should match the value you plan to use in production rank_embeddings_by_nmi_cosine calls.')
    bootstrap_iterations: float = Field(None, description='Bootstrap iterations per NMI computation during calibration grid search. Kept lower than single-pair calls because it is applied across all triplets and all grid points.')


class CalibrateNmiCosineWeightForCorpusTool(BaseTool):
    name: str = "nexus_similarity_search_api_calibrate_nmi_cosine_weight_for_corpus"
    description: str = 'Given a labeled calibration set of (query, positive_candidate, negative_candidate) triplets and their embeddings, finds the optimal nmi_cosine_weight w that maximizes separation between positive and negative pairs under the hybrid scoring function, reporting the optimal w with its bootstrap confidence interval and the resulting AUC-ROC. Use once before deploying rank_embeddings_by_nmi_cosine on a specific embedding model and domain to select the best w rather than using the default 0.5. Do NOT use as a runtime call per request — this is a one-time offline calibration step. Requires labeled triplets; if no labels are available, skip and use the default weight.'
    args_schema: type[BaseModel] = CalibrateNmiCosineWeightForCorpusInput

    def _run(self, triplets, weight_search_grid_size, discretization_bins, bootstrap_iterations) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_calibrate_nmi_cosine_weight_for_corpus", {"triplets": triplets, "weight_search_grid_size": weight_search_grid_size, "discretization_bins": discretization_bins, "bootstrap_iterations": bootstrap_iterations})