"""
nexus-similarity-search-api — CrewAI Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.crewai_tool import RankHybridSimilarityTool

    @agent
    class MyAgent(Agent):
        tools = [RankHybridSimilarityTool()]
"""

from typing import Any
from crewai_tools import BaseTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class RankHybridSimilarityInput(BaseModel):
    query: str = Field(..., description='JSON-encoded object representing the query record. Keys are feature names; values are strings (categorical) or numbers (continuous). Must share at least one key with corpus records.')
    corpus: str = Field(..., description='JSON-encoded array of objects. Each object is a candidate record with the same schema as query. Minimum 2 records, maximum 50000 records per call.')
    top_k: float = Field(None, description='Number of top-ranked results to return. Must be between 1 and the corpus size. Defaults to 10.')
    score_breakdown: bool = Field(None, description='If true, each result includes per-component scores: nmi_score, cosine_score, nmi_weight, cosine_weight, and per-feature NMI contributions. Adds latency proportional to feature count. Defaults to false.')


class RankHybridSimilarityTool(BaseTool):
    name: str = "nexus_similarity_search_api_rank_hybrid_similarity"
    description: str = 'Ranks a corpus of records by hybrid similarity to a query record, fusing NMI for categorical/discrete features and cosine similarity for continuous features into a single adaptive-weighted score. Use when your payload contains a mix of categorical and numeric fields and you need ranked results with per-component score explanation. Do NOT use for pure text embedding search, for corpora larger than 50,000 records per call, or when you need persistent index storage between calls.'
    args_schema: type[BaseModel] = RankHybridSimilarityInput

    def _run(self, query, corpus, top_k, score_breakdown) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_rank_hybrid_similarity", {"query": query, "corpus": corpus, "top_k": top_k, "score_breakdown": score_breakdown})

class ComputePairwiseHybridMatrixInput(BaseModel):
    records: str = Field(..., description='JSON-encoded array of objects. Each object is a record with string (categorical) or numeric (continuous) values. All records must share at least 2 common keys. Maximum 2000 records.')
    include_diagonal: bool = Field(None, description='If true, diagonal entries (self-similarity = 1.0) are included in the output matrix. Set to false when passing the matrix directly to clustering algorithms that assume zero diagonal. Defaults to true.')


class ComputePairwiseHybridMatrixTool(BaseTool):
    name: str = "nexus_similarity_search_api_compute_pairwise_hybrid_matrix"
    description: str = 'Computes the full N×N hybrid similarity matrix for a set of records using the same NMI+cosine adaptive fusion. Use for clustering preprocessing, graph construction, or any workflow that needs all pairwise distances in one call. Do NOT use when N > 2000 (O(N^2) complexity becomes prohibitive) or when you only need a single query ranked against a corpus — use rank_hybrid_similarity instead.'
    args_schema: type[BaseModel] = ComputePairwiseHybridMatrixInput

    def _run(self, records, include_diagonal) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_compute_pairwise_hybrid_matrix", {"records": records, "include_diagonal": include_diagonal})

class ExplainFeatureWeightCalibrationInput(BaseModel):
    sample_records: str = Field(..., description='JSON-encoded array of at least 10 representative records from your dataset. Used to estimate marginal entropies and variance. Maximum 5000 records.')


class ExplainFeatureWeightCalibrationTool(BaseTool):
    name: str = "nexus_similarity_search_api_explain_feature_weight_calibration"
    description: str = 'Given a sample of records, returns the adaptive weight assigned to each feature under the NMI+cosine fusion model: marginal entropy for categoricals, L2 norm variance for numerics, and the resulting nmi_weight/cosine_weight split. Use for auditing or understanding why the model weights features as it does before running a large ranking job. Do NOT use as a substitute for actual similarity computation — weights here are descriptive, not prescriptive overrides.'
    args_schema: type[BaseModel] = ExplainFeatureWeightCalibrationInput

    def _run(self, sample_records) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_explain_feature_weight_calibration", {"sample_records": sample_records})

class FilterByHybridThresholdInput(BaseModel):
    query: str = Field(..., description='JSON-encoded object representing the query record. Keys are feature names; values are strings (categorical) or numbers (continuous).')
    corpus: str = Field(..., description='JSON-encoded array of candidate records. Maximum 50000 records per call.')
    min_hybrid_score: float = Field(..., description='Minimum hybrid similarity score [0.0, 1.0] a record must exceed to be included in the result. Values below 0.05 risk returning the full corpus.')
    score_breakdown: bool = Field(None, description='If true, each returned record includes nmi_score, cosine_score, and component weights alongside the hybrid_score. Defaults to false.')


class FilterByHybridThresholdTool(BaseTool):
    name: str = "nexus_similarity_search_api_filter_by_hybrid_threshold"
    description: str = 'Returns all corpus records whose hybrid similarity to the query exceeds a minimum threshold, without ranking. Use when you need a membership decision (similar/not-similar) rather than a ranked list, e.g., deduplication, near-duplicate detection, or candidate set construction. Do NOT use when you need a ranked ordering — rank_hybrid_similarity is more appropriate. Do NOT use with thresholds below 0.05 on high-cardinality categorical corpora, as recall will be near-total and the result set will be unmanageably large.'
    args_schema: type[BaseModel] = FilterByHybridThresholdInput

    def _run(self, query, corpus, min_hybrid_score, score_breakdown) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_filter_by_hybrid_threshold", {"query": query, "corpus": corpus, "min_hybrid_score": min_hybrid_score, "score_breakdown": score_breakdown})

class DetectFeatureTypeSchemaInput(BaseModel):
    sample_records: str = Field(..., description='JSON-encoded array of at least 5 representative records. More records yield more reliable type detection for low-frequency categorical values. Maximum 5000 records.')
    override_types: str = Field(None, description='Optional JSON-encoded object mapping feature names to forced types: \'categorical\' or \'continuous\'. Use to correct misclassifications on ambiguous integer-coded fields. Example: {"zip_code": "categorical"}. Pass null to skip.')


class DetectFeatureTypeSchemaTool(BaseTool):
    name: str = "nexus_similarity_search_api_detect_feature_type_schema"
    description: str = 'Analyzes a sample of records and returns the inferred type (categorical or continuous) and entropy/variance statistics for each feature key, exactly as the similarity engine would classify them internally. Use before a ranking or filtering call to validate that the engine will treat your features as intended, especially for ambiguous fields (e.g., integer codes that should be categorical). Do NOT use as a general-purpose schema inference tool — it only classifies features into the two types the similarity model supports.'
    args_schema: type[BaseModel] = DetectFeatureTypeSchemaInput

    def _run(self, sample_records, override_types) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_detect_feature_type_schema", {"sample_records": sample_records, "override_types": override_types})