"""
nexus-similarity-search-api — CrewAI Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.crewai_tool import RankVectorsByNmiCosineTool

    @agent
    class MyAgent(Agent):
        tools = [RankVectorsByNmiCosineTool()]
"""

from typing import Any
from crewai_tools import BaseTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class RankVectorsByNmiCosineInput(BaseModel):
    query_vector: list[float] = Field(..., description='Query vector as a flat list of floats. Must match dimensionality of all corpus vectors.')
    corpus_vectors: list[list[float]] = Field(..., description='List of candidate vectors to rank. Each inner list must have the same length as query_vector. Maximum 50,000 rows.')
    nmi_threshold: float = Field(None, description='Minimum NMI score [0.0–1.0] a feature dimension must achieve to be included in cosine computation. Higher values are more aggressive at dropping noisy features. Recommended range 0.05–0.30.')
    top_k: float = Field(None, description='Number of top-ranked results to return. Must be between 1 and the corpus size.')
    confidence_level: float = Field(None, description='Confidence level for the returned similarity score interval, derived from empirical NMI distribution. Typical values: 0.90, 0.95, 0.99.')


class RankVectorsByNmiCosineTool(BaseTool):
    name: str = "nexus_similarity_search_api_rank_vectors_by_nmi_cosine"
    description: str = 'Ranks a corpus of vectors against a query vector using NMI-filtered cosine similarity. NMI is computed per-feature across the corpus to suppress noisy dimensions before distance calculation. Use this when you have raw numerical feature vectors and want ranked similarity with confidence intervals. Do NOT use for text inputs (use tokenized_corpus_similarity instead), and do NOT use when corpus size exceeds 50,000 vectors per call — batch instead.'
    args_schema: type[BaseModel] = RankVectorsByNmiCosineInput

    def _run(self, query_vector, corpus_vectors, nmi_threshold, top_k, confidence_level) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_rank_vectors_by_nmi_cosine", {"query_vector": query_vector, "corpus_vectors": corpus_vectors, "nmi_threshold": nmi_threshold, "top_k": top_k, "confidence_level": confidence_level})

class ComputeTokenizedCorpusSimilarityInput(BaseModel):
    query_token_features: list[float] = Field(..., description='Query document represented as a feature vector over vocabulary (e.g., TF-IDF weights or binary term presence). Length defines vocabulary size.')
    corpus_token_features: list[list[float]] = Field(..., description='Corpus documents as feature vectors over the same vocabulary as query_token_features. All rows must share vocabulary length.')
    nmi_bins: float = Field(None, description='Number of histogram bins used when discretizing continuous feature values to compute NMI. Higher bins increase NMI resolution but add compute cost. Meaningful range: 5–50.')
    top_k: float = Field(None, description='Number of top-ranked results to return.')
    confidence_level: float = Field(None, description='Confidence level for the returned per-result similarity confidence interval.')


class ComputeTokenizedCorpusSimilarityTool(BaseTool):
    name: str = "nexus_similarity_search_api_compute_tokenized_corpus_similarity"
    description: str = 'Accepts pre-tokenized text sequences (lists of token IDs or term-frequency feature arrays) and ranks them against a query sequence using NMI-weighted cosine. NMI is computed over the token co-occurrence feature space to prune uninformative vocabulary dimensions. Use this for sparse text feature vectors or BoW/TF-IDF representations. Do NOT use with dense embedding vectors (use rank_vectors_by_nmi_cosine) and do NOT pass raw strings — tokenize first.'
    args_schema: type[BaseModel] = ComputeTokenizedCorpusSimilarityInput

    def _run(self, query_token_features, corpus_token_features, nmi_bins, top_k, confidence_level) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_compute_tokenized_corpus_similarity", {"query_token_features": query_token_features, "corpus_token_features": corpus_token_features, "nmi_bins": nmi_bins, "top_k": top_k, "confidence_level": confidence_level})

class ExtractNmiFeatureWeightsInput(BaseModel):
    query_vector: list[float] = Field(..., description='Query vector defining the reference distribution for NMI computation across corpus dimensions.')
    corpus_vectors: list[list[float]] = Field(..., description='Corpus used to estimate the empirical feature distributions needed for NMI. Same shape constraints as rank_vectors_by_nmi_cosine.')
    nmi_bins: float = Field(None, description='Number of histogram bins for NMI discretization. Consistent with the bins used in downstream ranking calls.')
    return_top_n_dimensions: float = Field(None, description='Return only the top-N highest-NMI feature indices and their scores, sorted descending. Returns all dimensions if omitted.')


class ExtractNmiFeatureWeightsTool(BaseTool):
    name: str = "nexus_similarity_search_api_extract_nmi_feature_weights"
    description: str = 'Computes per-dimension NMI scores between a query vector and a corpus, returning the weight assigned to each feature dimension without performing similarity ranking. Use this to audit which features drive the NMI-cosine score, to tune nmi_threshold before a full ranking call, or to pre-validate corpus quality. Do NOT use as a substitute for ranking — this endpoint returns weights only, not similarity scores.'
    args_schema: type[BaseModel] = ExtractNmiFeatureWeightsInput

    def _run(self, query_vector, corpus_vectors, nmi_bins, return_top_n_dimensions) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_extract_nmi_feature_weights", {"query_vector": query_vector, "corpus_vectors": corpus_vectors, "nmi_bins": nmi_bins, "return_top_n_dimensions": return_top_n_dimensions})

class CompareTabularRowSimilarityInput(BaseModel):
    query_row: list[float] = Field(..., description='Single query row as a list of numerically encoded feature values. Length must equal number of columns in corpus_rows.')
    corpus_rows: list[list[float]] = Field(..., description='Tabular corpus where each row is a candidate record with the same feature schema as query_row.')
    column_names: list[str] = Field(None, description='Optional column labels for each feature position. Used only for interpretability in the response payload — does not affect computation. Must match query_row length if provided.')
    nmi_threshold: float = Field(None, description='Minimum NMI score for a column to participate in cosine similarity. For tabular data with many correlated columns, values of 0.05–0.15 are typical.')
    top_k: float = Field(None, description='Number of most-similar rows to return, ranked by NMI-weighted cosine score.')
    confidence_level: float = Field(None, description='Confidence level for similarity score intervals.')


class CompareTabularRowSimilarityTool(BaseTool):
    name: str = "nexus_similarity_search_api_compare_tabular_row_similarity"
    description: str = 'Ranks rows in a tabular dataset (mixed numerical features, pre-encoded) against a query row using NMI-weighted cosine. Designed for structured tabular data where feature columns have heterogeneous scales. Handles per-column z-score normalization internally before NMI and cosine steps. Use for structured ML datasets, relational feature tables, or any input that originates as a dataframe row. Do NOT use for raw text or image embeddings — those have different distribution assumptions.'
    args_schema: type[BaseModel] = CompareTabularRowSimilarityInput

    def _run(self, query_row, corpus_rows, column_names, nmi_threshold, top_k, confidence_level) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_compare_tabular_row_similarity", {"query_row": query_row, "corpus_rows": corpus_rows, "column_names": column_names, "nmi_threshold": nmi_threshold, "top_k": top_k, "confidence_level": confidence_level})

class EstimateSimilarityConfidenceBandInput(BaseModel):
    similarity_scores: list[float] = Field(..., description='List of raw NMI-weighted cosine similarity scores from a prior ranking call, in [−1.0, 1.0].')
    nmi_weight_distribution: list[float] = Field(..., description='Per-dimension NMI weights used to produce the scores. Returned by extract_nmi_feature_weights or included in rank_vectors_by_nmi_cosine response.')
    confidence_level: float = Field(None, description='Target confidence level for the output bands. Can differ from the level used in the original ranking call.')
    bootstrap_iterations: float = Field(None, description='Number of bootstrap resampling iterations for band estimation. Higher values reduce Monte Carlo variance at compute cost. Range 100–5000.')


class EstimateSimilarityConfidenceBandTool(BaseTool):
    name: str = "nexus_similarity_search_api_estimate_similarity_confidence_band"
    description: str = 'Given a set of pre-computed NMI-cosine similarity scores and the underlying NMI weight distribution, returns bootstrap-derived confidence bands for each score. Use this when you already have scores from a prior ranking call and want to widen or narrow confidence intervals at a different confidence level, or to validate stability of results under resampling. Do NOT use as a primary similarity computation — this endpoint takes scores as input, not raw vectors.'
    args_schema: type[BaseModel] = EstimateSimilarityConfidenceBandInput

    def _run(self, similarity_scores, nmi_weight_distribution, confidence_level, bootstrap_iterations) -> Any:
        return call_mcp_tool("nexus_similarity_search_api_estimate_similarity_confidence_band", {"similarity_scores": similarity_scores, "nmi_weight_distribution": nmi_weight_distribution, "confidence_level": confidence_level, "bootstrap_iterations": bootstrap_iterations})