"""
nexus-similarity-search-api — LangChain Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.langchain_tool import rank_by_nmi_cosine_composite_tool, compare_embedding_pair_significance_tool, estimate_corpus_anisotropy_tool, filter_spurious_cosine_matches_tool, calibrate_pvalue_null_distribution_tool
    agent = initialize_agent([rank_by_nmi_cosine_composite_tool, compare_embedding_pair_significance_tool, estimate_corpus_anisotropy_tool, filter_spurious_cosine_matches_tool, calibrate_pvalue_null_distribution_tool], llm,
                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)
"""

from typing import Any
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class RankByNmiCosineCompositeInput(BaseModel):
    query_embedding: list[float] = Field(..., description='Dense float vector representing the query item. Must match dimensionality of all candidate_embeddings vectors. Typically 128–4096 dims depending on model.')
    candidate_embeddings: list[list[float]] = Field(..., description='2-D array of candidate float vectors to rank. Each row is one embedding. All rows must share the same dimensionality as query_embedding. Minimum 30 rows for reliable p-value calibration.')
    histogram_bins: float = Field(None, description="Number of bins used to discretize each embedding's activation distribution before computing NMI. Higher values increase NMI resolution but raise compute cost. Typical range 8–64; default 16 balances precision vs. speed.")
    alpha: float = Field(None, description="Significance threshold for the calibrated p-value. Results with p > alpha are flagged as statistically non-significant. Does not filter results, only sets the 'significant' boolean field in each result row.")
    top_k: float = Field(None, description='Maximum number of top-ranked results to return, ordered by composite score descending. Set to 0 to return all candidates.')
    composite_weight_nmi: float = Field(None, description='Weight assigned to normalized NMI in the composite score formula: composite = (1 - w) * cosine + w * nmi_normalized. Weight for cosine is implicitly (1 - composite_weight_nmi). Use higher values when embedding space is known to be anisotropic or cluster-dense.')


def _rank_by_nmi_cosine_composite_impl(query_embedding, candidate_embeddings, histogram_bins, alpha, top_k, composite_weight_nmi) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_rank_by_nmi_cosine_composite", {"query_embedding": query_embedding, "candidate_embeddings": candidate_embeddings, "histogram_bins": histogram_bins, "alpha": alpha, "top_k": top_k, "composite_weight_nmi": composite_weight_nmi})


rank_by_nmi_cosine_composite_tool = StructuredTool.from_function(
    func=_rank_by_nmi_cosine_composite_impl,
    name="nexus_similarity_search_api_rank_by_nmi_cosine_composite",
    description='Ranks a corpus of candidate embeddings against a query embedding using a composite score that fuses cosine similarity with normalized mutual information (NMI) computed over activation-histogram distributions of each embedding. Returns ranked candidates with composite score, raw cosine, raw NMI, and calibrated p-value indicating whether the similarity is statistically significant given corpus size. Use when you need to distinguish genuine semantic similarity from spatial correlation artifacts in dense embedding subspaces. Do NOT use for exact nearest-neighbor lookup where statistical significance is irrelevant, or when corpus has fewer than 30 vectors (p-value calibration degrades below this threshold).',
    args_schema=RankByNmiCosineCompositeInput,
)

class CompareEmbeddingPairSignificanceInput(BaseModel):
    embedding_a: list[float] = Field(..., description='First embedding vector of the pair being tested. Dimensionality must match embedding_b and all reference_corpus vectors.')
    embedding_b: list[float] = Field(..., description='Second embedding vector of the pair being tested.')
    reference_corpus: list[list[float]] = Field(..., description='Background corpus of embeddings used to build the null distribution for p-value calibration. Must have at least 30 rows. Not ranked or scored — used only for statistical reference.')
    histogram_bins: float = Field(None, description='Bin count for activation-histogram discretization, consistent with what was used in any prior ranking call for comparability.')


def _compare_embedding_pair_significance_impl(embedding_a, embedding_b, reference_corpus, histogram_bins) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_compare_embedding_pair_significance", {"embedding_a": embedding_a, "embedding_b": embedding_b, "reference_corpus": reference_corpus, "histogram_bins": histogram_bins})


compare_embedding_pair_significance_tool = StructuredTool.from_function(
    func=_compare_embedding_pair_significance_impl,
    name="nexus_similarity_search_api_compare_embedding_pair_significance",
    description="Computes the composite similarity score and calibrated p-value for exactly one query-candidate pair, given a reference corpus used solely for null-distribution calibration. Use when you need to audit a single pair's similarity in isolation — e.g., deduplication checks, plagiarism signals, or validating a specific match from a prior ranking call. Do NOT use as a batch ranking method (use rank_by_nmi_cosine_composite instead); invoking this tool in a loop over N candidates is O(N) API calls and defeats the purpose.",
    args_schema=CompareEmbeddingPairSignificanceInput,
)

class EstimateCorpusAnisotropyInput(BaseModel):
    corpus_embeddings: list[list[float]] = Field(..., description='Full corpus of embeddings to analyze. Minimum 30 vectors required for meaningful PCA-based anisotropy estimation. Sampling a representative subset is acceptable for large corpora.')
    pca_components: float = Field(None, description='Number of principal components to inspect when computing explained-variance ratio. Set to a value that covers the subspace you suspect is dominant (e.g., 10–50 for typical transformer embeddings).')


def _estimate_corpus_anisotropy_impl(corpus_embeddings, pca_components) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_estimate_corpus_anisotropy", {"corpus_embeddings": corpus_embeddings, "pca_components": pca_components})


estimate_corpus_anisotropy_tool = StructuredTool.from_function(
    func=_estimate_corpus_anisotropy_impl,
    name="nexus_similarity_search_api_estimate_corpus_anisotropy",
    description='Analyzes a corpus of embeddings to quantify anisotropy — the degree to which embeddings cluster in a low-dimensional subspace, which inflates cosine similarity scores for unrelated items. Returns the explained-variance ratio of the top principal components, average pairwise cosine baseline, and a recommended composite_weight_nmi value to compensate for the measured anisotropy. Use this BEFORE your first ranking call on a new corpus to calibrate composite_weight_nmi appropriately. Do NOT use as a substitute for actual similarity ranking — it produces diagnostics, not similarity scores.',
    args_schema=EstimateCorpusAnisotropyInput,
)

class FilterSpuriousCosineMatchesInput(BaseModel):
    query_embedding: list[float] = Field(..., description='The original query embedding used to produce the cosine-ranked candidate list.')
    candidate_embeddings: list[list[float]] = Field(..., description='Embeddings of the pre-ranked candidates, in the same order as cosine_scores. Must have the same number of rows as cosine_scores.')
    cosine_scores: list[float] = Field(..., description='Pre-computed cosine similarity scores for each candidate, parallel to candidate_embeddings. Values must be in [-1.0, 1.0]. Passed in to avoid redundant recomputation.')
    min_composite_score: float = Field(None, description='Minimum composite score threshold below which a candidate is classified as a spurious match and excluded from the output. Candidates at or above this value are retained and re-ranked.')
    histogram_bins: float = Field(None, description='Bin count for NMI histogram discretization. Should match the value used in any prior ranking call for score consistency.')


def _filter_spurious_cosine_matches_impl(query_embedding, candidate_embeddings, cosine_scores, min_composite_score, histogram_bins) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_filter_spurious_cosine_matches", {"query_embedding": query_embedding, "candidate_embeddings": candidate_embeddings, "cosine_scores": cosine_scores, "min_composite_score": min_composite_score, "histogram_bins": histogram_bins})


filter_spurious_cosine_matches_tool = StructuredTool.from_function(
    func=_filter_spurious_cosine_matches_impl,
    name="nexus_similarity_search_api_filter_spurious_cosine_matches",
    description='Given a pre-ranked list of (candidate_index, cosine_score) pairs and the corresponding embeddings, recomputes NMI for each pair and removes matches whose composite score drops below a significance threshold — i.e., matches that were high-cosine but low-NMI, indicating spatial correlation rather than informational dependence. Returns the filtered and re-ranked list with composite scores and p-values. Use as a post-processing step on results from any cosine-only retrieval system (FAISS, Pinecone, etc.) to remove false positives before surfacing results to end users. Do NOT use as a primary ranking method when you have access to raw embeddings upfront — use rank_by_nmi_cosine_composite directly instead.',
    args_schema=FilterSpuriousCosineMatchesInput,
)

class CalibratePvalueNullDistributionInput(BaseModel):
    corpus_embeddings: list[list[float]] = Field(..., description='Full corpus of embeddings from which random pairs are sampled to build the null distribution. Minimum 50 vectors for stable distribution fitting.')
    n_null_samples: float = Field(None, description='Number of random pairs to sample from the corpus when constructing the null distribution. More samples produce a more stable p-value calibration at higher compute cost. 500–2000 is typical.')
    histogram_bins: float = Field(None, description='Bin count for NMI discretization, must match the value you intend to use in subsequent ranking calls for calibration to be valid.')
    composite_weight_nmi: float = Field(None, description='NMI weight used in composite scoring, must match the value you intend to use in subsequent ranking calls.')


def _calibrate_pvalue_null_distribution_impl(corpus_embeddings, n_null_samples, histogram_bins, composite_weight_nmi) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_calibrate_pvalue_null_distribution", {"corpus_embeddings": corpus_embeddings, "n_null_samples": n_null_samples, "histogram_bins": histogram_bins, "composite_weight_nmi": composite_weight_nmi})


calibrate_pvalue_null_distribution_tool = StructuredTool.from_function(
    func=_calibrate_pvalue_null_distribution_impl,
    name="nexus_similarity_search_api_calibrate_pvalue_null_distribution",
    description='Precomputes the null distribution of composite similarity scores for a given corpus by sampling random pairs and fitting a parametric distribution (beta or gamma) to their composite scores. Returns the distribution parameters and a lookup table of composite-score-to-p-value mappings. Use this once per stable corpus to cache calibration parameters and pass them to ranking calls, avoiding redundant null-distribution recomputation on every query. Do NOT call this on every query — it is intended for one-time or periodic calibration when corpus membership changes significantly (more than 10% churn).',
    args_schema=CalibratePvalueNullDistributionInput,
)