"""
nexus-similarity-search-api — LangChain Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.langchain_tool import rank_by_nmi_weighted_cosine_tool, compute_pairwise_nmi_matrix_tool, score_heterogeneous_pair_tool, filter_candidates_by_nmi_threshold_tool, benchmark_nmi_vs_cosine_delta_tool
    agent = initialize_agent([rank_by_nmi_weighted_cosine_tool, compute_pairwise_nmi_matrix_tool, score_heterogeneous_pair_tool, filter_candidates_by_nmi_threshold_tool, benchmark_nmi_vs_cosine_delta_tool], llm,
                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)
"""

from typing import Any
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class RankByNmiWeightedCosineInput(BaseModel):
    query_vector: list[float] = Field(..., description='Dense numeric representation of the query item. Must match dimensionality of all candidate vectors.')
    candidate_vectors: list[list[float]] = Field(..., description='Collection of candidate dense vectors to rank against the query. Each row must have the same length as query_vector.')
    candidate_ids: list[str] = Field(..., description='Stable identifiers for each candidate vector, returned in ranked output. Must be same length as candidate_vectors.')
    nmi_bins: float = Field(None, description='Number of histogram bins used when estimating marginal and joint distributions for NMI computation per feature dimension. Higher values increase precision for continuous features but raise compute cost. Recommended range 5-20.')
    top_k: float = Field(None, description='Maximum number of ranked results to return. Results are sorted descending by NMI-weighted cosine score.')


def _rank_by_nmi_weighted_cosine_impl(query_vector, candidate_vectors, candidate_ids, nmi_bins, top_k) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_rank_by_nmi_weighted_cosine", {"query_vector": query_vector, "candidate_vectors": candidate_vectors, "candidate_ids": candidate_ids, "nmi_bins": nmi_bins, "top_k": top_k})


rank_by_nmi_weighted_cosine_tool = StructuredTool.from_function(
    func=_rank_by_nmi_weighted_cosine_impl,
    name="nexus_similarity_search_api_rank_by_nmi_weighted_cosine",
    description='Computes NMI-weighted cosine similarity between a query vector and a candidate collection, returning ranked results in a single stateless HTTP call. Use when the feature space is heterogeneous (mixed numeric, categorical, or multimodal) and standard cosine underperforms due to non-linear dependencies. Do NOT use for pure text embeddings where cosine is sufficient, or when you need approximate nearest-neighbor at >1M candidates per call (latency will degrade beyond practical limits).',
    args_schema=RankByNmiWeightedCosineInput,
)

class ComputePairwiseNmiMatrixInput(BaseModel):
    vectors: list[list[float]] = Field(..., description='Collection of vectors from which feature-level NMI weights are derived. Each row is one sample; each column is one feature dimension.')
    nmi_bins: float = Field(None, description='Histogram bins per feature dimension used to estimate joint and marginal distributions. Increase for continuous features with wide range, decrease for near-binary features.')
    normalize_weights: bool = Field(None, description='If true, returns NMI values normalized to [0,1] per dimension pair. If false, returns raw joint entropy ratios. Set true when you intend to feed output directly into rank_by_nmi_weighted_cosine as custom weights.')


def _compute_pairwise_nmi_matrix_impl(vectors, nmi_bins, normalize_weights) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_compute_pairwise_nmi_matrix", {"vectors": vectors, "nmi_bins": nmi_bins, "normalize_weights": normalize_weights})


compute_pairwise_nmi_matrix_tool = StructuredTool.from_function(
    func=_compute_pairwise_nmi_matrix_impl,
    name="nexus_similarity_search_api_compute_pairwise_nmi_matrix",
    description='Computes the full NMI matrix across feature dimensions for a given collection, exposing per-feature mutual information weights without performing a search. Use this to inspect which feature dimensions carry the most discriminative mutual information before invoking rank_by_nmi_weighted_cosine, or to debug why certain features dominate weighting. Do NOT use as a replacement for the ranked search — this returns a DxD weight matrix, not similarity scores between items.',
    args_schema=ComputePairwiseNmiMatrixInput,
)

class ScoreHeterogeneousPairInput(BaseModel):
    vector_a: list[float] = Field(..., description='First dense vector of the pair. Treated as query in the NMI weight derivation.')
    vector_b: list[float] = Field(..., description='Second dense vector of the pair. Must match dimensionality of vector_a.')
    nmi_bins: float = Field(None, description='Histogram bins used to estimate per-dimension marginal distributions from the two vectors. Lower values smooth distributions; higher values respect fine structure.')
    return_dimension_weights: bool = Field(None, description='If true, the response includes the NMI weight assigned to each feature dimension, enabling full score decomposition.')


def _score_heterogeneous_pair_impl(vector_a, vector_b, nmi_bins, return_dimension_weights) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_score_heterogeneous_pair", {"vector_a": vector_a, "vector_b": vector_b, "nmi_bins": nmi_bins, "return_dimension_weights": return_dimension_weights})


score_heterogeneous_pair_tool = StructuredTool.from_function(
    func=_score_heterogeneous_pair_impl,
    name="nexus_similarity_search_api_score_heterogeneous_pair",
    description='Computes the NMI-weighted cosine similarity score for exactly one query-candidate pair with full per-dimension weight breakdown. Use for explainability: when you need to understand why two specific items score high or low, or to validate that NMI weighting is behaving correctly on a known pair. Do NOT use in batch loops to simulate collection ranking — rank_by_nmi_weighted_cosine is vectorized and orders of magnitude faster for that purpose.',
    args_schema=ScoreHeterogeneousPairInput,
)

class FilterCandidatesByNmiThresholdInput(BaseModel):
    query_vector: list[float] = Field(..., description='Dense query vector. Must match dimensionality of all candidate vectors.')
    candidate_vectors: list[list[float]] = Field(..., description='Collection of candidate dense vectors to evaluate against the threshold.')
    candidate_ids: list[str] = Field(..., description='Stable identifiers for each candidate vector. Must be same length as candidate_vectors.')
    min_score_threshold: float = Field(..., description='Minimum NMI-weighted cosine score [0.0, 1.0] a candidate must reach to be included in the response. Values below 0.3 may return very large result sets on heterogeneous collections.')
    nmi_bins: float = Field(None, description='Histogram bins for NMI estimation per feature dimension.')


def _filter_candidates_by_nmi_threshold_impl(query_vector, candidate_vectors, candidate_ids, min_score_threshold, nmi_bins) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_filter_candidates_by_nmi_threshold", {"query_vector": query_vector, "candidate_vectors": candidate_vectors, "candidate_ids": candidate_ids, "min_score_threshold": min_score_threshold, "nmi_bins": nmi_bins})


filter_candidates_by_nmi_threshold_tool = StructuredTool.from_function(
    func=_filter_candidates_by_nmi_threshold_impl,
    name="nexus_similarity_search_api_filter_candidates_by_nmi_threshold",
    description='Returns only candidates whose NMI-weighted cosine score meets or exceeds a minimum threshold, without a fixed top_k cutoff. Use when downstream logic requires a quality floor rather than a fixed result count — e.g., deduplication pipelines, semantic clustering seeding, or anomaly filtering where you want all sufficiently similar items. Do NOT use when you need exactly K results; use rank_by_nmi_weighted_cosine with top_k instead.',
    args_schema=FilterCandidatesByNmiThresholdInput,
)

class BenchmarkNmiVsCosineDeltaInput(BaseModel):
    query_vector: list[float] = Field(..., description='Dense query vector used in both cosine and NMI-weighted cosine evaluations.')
    candidate_vectors: list[list[float]] = Field(..., description='Collection of candidate dense vectors to rank under both metrics.')
    candidate_ids: list[str] = Field(..., description='Stable identifiers for each candidate. Must be same length as candidate_vectors.')
    nmi_bins: float = Field(None, description='Histogram bins for NMI estimation. Applies only to the NMI-weighted cosine branch of the benchmark.')
    top_k: float = Field(None, description='Number of top candidates to include in the delta comparison output. Full collection is still ranked internally.')


def _benchmark_nmi_vs_cosine_delta_impl(query_vector, candidate_vectors, candidate_ids, nmi_bins, top_k) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_benchmark_nmi_vs_cosine_delta", {"query_vector": query_vector, "candidate_vectors": candidate_vectors, "candidate_ids": candidate_ids, "nmi_bins": nmi_bins, "top_k": top_k})


benchmark_nmi_vs_cosine_delta_tool = StructuredTool.from_function(
    func=_benchmark_nmi_vs_cosine_delta_impl,
    name="nexus_similarity_search_api_benchmark_nmi_vs_cosine_delta",
    description='Runs both pure cosine and NMI-weighted cosine ranking on the same query and candidates, returning side-by-side rank positions and score deltas per candidate. Use to quantify how much NMI weighting changes ranking order for a specific dataset — critical for justifying adoption to stakeholders or detecting feature spaces where cosine already suffices. Do NOT use in production ranking pipelines — this endpoint is designed for evaluation and costs roughly 2x the compute of a single ranking call.',
    args_schema=BenchmarkNmiVsCosineDeltaInput,
)