"""
nexus-similarity-search-api — LangChain Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.langchain_tool import rank_embeddings_by_nmi_cosine_tool, compute_pairwise_nmi_cosine_matrix_tool, score_embedding_pair_nmi_cosine_tool, calibrate_domain_nmi_cosine_weights_tool, explain_nmi_cosine_rank_divergence_tool
    agent = initialize_agent([rank_embeddings_by_nmi_cosine_tool, compute_pairwise_nmi_cosine_matrix_tool, score_embedding_pair_nmi_cosine_tool, calibrate_domain_nmi_cosine_weights_tool, explain_nmi_cosine_rank_divergence_tool], llm,
                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)
"""

from typing import Any
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class RankEmbeddingsByNmiCosineInput(BaseModel):
    query_embedding: list[float] = Field(..., description='Dense float vector representing the query. Must match dimensionality of all candidate_embeddings.')
    candidate_embeddings: list[list[float]] = Field(..., description='List of dense float vectors to rank against the query. Each inner array must have the same length as query_embedding.')
    domain: str = Field(..., description="Embedding domain that controls the learned NMI/cosine weight mix. Accepted values: 'text', 'image', 'tabular'. Determines alpha_nmi and alpha_cosine from pretrained domain calibration.")
    top_k: float = Field(None, description='Number of top-ranked candidates to return. Must be <= len(candidate_embeddings).')
    return_scores: bool = Field(None, description='If true, includes composite score, nmi_component, and cosine_component for each result. Set false to reduce payload size when only rank order matters.')


def _rank_embeddings_by_nmi_cosine_impl(query_embedding, candidate_embeddings, domain, top_k, return_scores) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_rank_embeddings_by_nmi_cosine", {"query_embedding": query_embedding, "candidate_embeddings": candidate_embeddings, "domain": domain, "top_k": top_k, "return_scores": return_scores})


rank_embeddings_by_nmi_cosine_tool = StructuredTool.from_function(
    func=_rank_embeddings_by_nmi_cosine_impl,
    name="nexus_similarity_search_api_rank_embeddings_by_nmi_cosine",
    description='Ranks a set of candidate embeddings against a query embedding using a weighted NMI+Cosine composite score calibrated per domain. Use when you need stateless semantic similarity ranking without a vector index or upsert step, especially when candidate correlations are non-linear. Do NOT use if you have a persistent vector store already indexed — latency will be higher than ANN retrieval for corpora above 50k vectors.',
    args_schema=RankEmbeddingsByNmiCosineInput,
)

class ComputePairwiseNmiCosineMatrixInput(BaseModel):
    embeddings: list[list[float]] = Field(..., description='Set of dense float vectors for which to compute all pairwise composite scores. All vectors must share the same dimensionality.')
    domain: str = Field(..., description="Embedding domain controlling the NMI/cosine weight calibration. Accepted values: 'text', 'image', 'tabular'.")
    normalize_output: bool = Field(None, description='If true, min-max normalizes the composite matrix to [0, 1] per row. Set false to preserve raw composite scores for downstream calibration.')


def _compute_pairwise_nmi_cosine_matrix_impl(embeddings, domain, normalize_output) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_compute_pairwise_nmi_cosine_matrix", {"embeddings": embeddings, "domain": domain, "normalize_output": normalize_output})


compute_pairwise_nmi_cosine_matrix_tool = StructuredTool.from_function(
    func=_compute_pairwise_nmi_cosine_matrix_impl,
    name="nexus_similarity_search_api_compute_pairwise_nmi_cosine_matrix",
    description='Computes the full N×N composite similarity matrix for a set of embeddings. Use for clustering preprocessing, graph construction, or reranking pipelines where every pair needs a score. Do NOT use for query-vs-corpus ranking (use rank_embeddings_by_nmi_cosine instead) — cost is O(N²) and grows quadratically.',
    args_schema=ComputePairwiseNmiCosineMatrixInput,
)

class ScoreEmbeddingPairNmiCosineInput(BaseModel):
    embedding_a: list[float] = Field(..., description='First dense float vector of the pair.')
    embedding_b: list[float] = Field(..., description='Second dense float vector of the pair. Must match dimensionality of embedding_a.')
    domain: str = Field(..., description="Embedding domain controlling calibrated weight mix. Accepted values: 'text', 'image', 'tabular'.")


def _score_embedding_pair_nmi_cosine_impl(embedding_a, embedding_b, domain) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_score_embedding_pair_nmi_cosine", {"embedding_a": embedding_a, "embedding_b": embedding_b, "domain": domain})


score_embedding_pair_nmi_cosine_tool = StructuredTool.from_function(
    func=_score_embedding_pair_nmi_cosine_impl,
    name="nexus_similarity_search_api_score_embedding_pair_nmi_cosine",
    description='Returns the decomposed composite similarity score (NMI component, cosine component, weighted composite) for exactly one pair of embeddings. Use for debugging, threshold calibration, or audit trails where you need interpretable component breakdown. Do NOT use in batch loops — use rank_embeddings_by_nmi_cosine or compute_pairwise_nmi_cosine_matrix for multiple pairs; per-call overhead makes looping expensive.',
    args_schema=ScoreEmbeddingPairNmiCosineInput,
)

class CalibrateDomainNmiCosineWeightsInput(BaseModel):
    anchor_embeddings: list[list[float]] = Field(..., description='Query-side embeddings for each relevance pair. Index-aligned with positive_embeddings and negative_embeddings.')
    positive_embeddings: list[list[float]] = Field(..., description='Embeddings of items labeled as relevant/similar to the corresponding anchor. Same length as anchor_embeddings.')
    negative_embeddings: list[list[float]] = Field(..., description='Embeddings of items labeled as non-relevant to the corresponding anchor. Same length as anchor_embeddings.')
    domain_label: str = Field(..., description='Identifier for the custom domain profile to be created. Used to reference this calibration in subsequent ranking calls via the domain parameter.')


def _calibrate_domain_nmi_cosine_weights_impl(anchor_embeddings, positive_embeddings, negative_embeddings, domain_label) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_calibrate_domain_nmi_cosine_weights", {"anchor_embeddings": anchor_embeddings, "positive_embeddings": positive_embeddings, "negative_embeddings": negative_embeddings, "domain_label": domain_label})


calibrate_domain_nmi_cosine_weights_tool = StructuredTool.from_function(
    func=_calibrate_domain_nmi_cosine_weights_impl,
    name="nexus_similarity_search_api_calibrate_domain_nmi_cosine_weights",
    description="Derives optimal alpha_nmi and alpha_cosine weights for a custom embedding domain by fitting the composite scorer to a labeled relevance dataset you supply. Use when 'text', 'image', and 'tabular' presets underperform on your specific embedding model or corpus distribution. Do NOT use at inference time — run once offline and cache the returned weight profile; recalibrate only when the embedding model changes.",
    args_schema=CalibrateDomainNmiCosineWeightsInput,
)

class ExplainNmiCosineRankDivergenceInput(BaseModel):
    query_embedding: list[float] = Field(..., description='Dense float vector representing the query.')
    candidate_embeddings: list[list[float]] = Field(..., description='Candidate dense float vectors to compare under both ranking methods.')
    domain: str = Field(..., description="Embedding domain for composite weight calibration. Accepted values: 'text', 'image', 'tabular', or a custom domain_label from calibrate_domain_nmi_cosine_weights.")
    top_k: float = Field(None, description='Number of candidates to include in the divergence report, taken from the top of the composite ranking.')


def _explain_nmi_cosine_rank_divergence_impl(query_embedding, candidate_embeddings, domain, top_k) -> Any:
    return call_mcp_tool("nexus_similarity_search_api_explain_nmi_cosine_rank_divergence", {"query_embedding": query_embedding, "candidate_embeddings": candidate_embeddings, "domain": domain, "top_k": top_k})


explain_nmi_cosine_rank_divergence_tool = StructuredTool.from_function(
    func=_explain_nmi_cosine_rank_divergence_impl,
    name="nexus_similarity_search_api_explain_nmi_cosine_rank_divergence",
    description='Given a query and candidates, returns a divergence report showing where NMI-informed ranking differs from pure-cosine ranking and why — quantifying non-linear dependency contribution per candidate. Use when auditing model behavior, justifying ranking decisions to stakeholders, or diagnosing unexpected rank positions. Do NOT use in latency-sensitive inference paths — this runs both rankers plus divergence attribution and is 2-3x slower than rank_embeddings_by_nmi_cosine alone.',
    args_schema=ExplainNmiCosineRankDivergenceInput,
)